# ***Trabalhando com Planilhas do Excel***

--------------------------------------------------------------------------------------------------

In [ ]:
import pandas as pd
import openpyxl as xlsx

Leituras dos arquivos e criação de cada dataframe (df):

In [12]:
df_aracaju = pd.read_excel('../datasets/Aracaju.xlsx',)
df_fortaleza = pd.read_excel('../datasets/Fortaleza.xlsx',)
df_natal = pd.read_excel('../datasets/Natal.xlsx',)
df_recife = pd.read_excel('../datasets/Recife.xlsx',)
df_salvador = pd.read_excel('../datasets/Salvador.xlsx',)

In [15]:
# Testando um df:
df_fortaleza

        Cidade       Data  Vendas  LojaID  Qtde
0    Fortaleza 2019-01-01   45.27    1002     2
1    Fortaleza 2019-01-01  115.61    1002     3
2    Fortaleza 2019-02-10   35.33    1004     3
3    Fortaleza 2019-02-10   20.95    1004     6
4    Fortaleza 2019-01-01   14.25    1004     6
..         ...        ...     ...     ...   ...
137  Fortaleza 2019-03-02   51.99     983     3
138  Fortaleza 2019-03-02  150.38     983     6
139  Fortaleza 2019-03-02  141.16     980     7
140  Fortaleza 2019-03-02  166.89     983     5
141  Fortaleza 2019-03-02  182.75     983     8

[142 rows x 5 columns]

--------------------------------------------------------------------------------------------------

# ***Unindo todos os valores de cada dataframe***

--------------------------------------------------------------------------------------------------

É possível juntar 'df' utilizando o método concat()

## concat()

É necessário que dentro de seus parâmetros, coloquemos dentro de uma lista os dataframes queremos concatenar.

In [16]:
df = pd.concat([df_aracaju, df_fortaleza, df_natal, df_recife, df_salvador])

## head()

In [21]:
# Checando o dataframe final:
df.head(21)

     Cidade       Data  Vendas  LojaID  Qtde
0   Aracaju 2018-01-01  142.00    1520     1
1   Aracaju 2018-01-01   14.21    1522     6
2   Aracaju 2018-01-01   71.55    1520     1
3   Aracaju 2018-01-01    3.01    1521     7
4   Aracaju 2018-01-01   24.51    1522     8
5   Aracaju 2018-01-01  156.20    1522     1
6   Aracaju 2018-01-01   35.50    1522     2
7   Aracaju 2019-01-01  172.22    1522     6
8   Aracaju 2019-01-01   12.16    1523     1
9   Aracaju 2019-01-01  149.36    1523     3
10  Aracaju 2019-01-01   42.34    1522     6
11  Aracaju 2019-01-01  161.53    1520     4
12  Aracaju 2019-01-01    9.78    1520     8
13  Aracaju 2018-01-01   43.45    1522    10
14  Aracaju 2018-01-01  148.21    1521     3
15  Aracaju 2018-01-01  153.28    1523     6
16  Aracaju 2018-01-01   37.68    1522    10
17  Aracaju 2018-01-01  162.19    1522     9
18  Aracaju 2018-01-01   32.14    1522     6
19  Aracaju 2018-01-01   43.96    1520     9
20  Aracaju 2018-01-01   39.86    1522     9

## tail()

In [20]:
df.tail(20)

       Cidade       Data  Vendas  LojaID  Qtde
220  Salvador 2019-01-02   42.71    1035     1
221  Salvador 2019-01-02  142.23    1035     2
222  Salvador 2019-01-02   43.96    1037     1
223  Salvador 2019-01-02   40.51    1037     2
224  Salvador 2019-01-02  178.30    1035     3
225  Salvador 2019-01-02   36.23    1035     1
226  Salvador 2019-01-02   38.32    1035     2
227  Salvador 2019-01-02   14.70    1035     1
228  Salvador 2019-01-02    6.87    1037     3
229  Salvador 2019-01-02   43.08    1036     2
230  Salvador 2019-01-03  184.69    1036     1
231  Salvador 2019-01-03   89.85    1034     2
232  Salvador 2019-01-03  167.76    1034     3
233  Salvador 2019-01-03  172.40    1036     2
234  Salvador 2019-01-03   48.39    1035     2
235  Salvador 2019-01-03   41.84    1034     1
236  Salvador 2019-01-03  126.29    1035     3
237  Salvador 2019-01-03   38.06    1036     3
238  Salvador 2019-01-03  139.64    1035     1
239  Salvador 2019-01-03  161.41    1037     3